#ifndef WEATHER_BACKGROUNDS_H
#define WEATHER_BACKGROUNDS_H

#include <stdint.h>

#define WEATHER_BACKGROUND_COUNT       8U
#define WEATHER_BACKGROUND_LOW_WIDTH   240U
#define WEATHER_BACKGROUND_LOW_HEIGHT  136U
#define WEATHER_BACKGROUND_LOW_BYTES   \
    (WEATHER_BACKGROUND_LOW_WIDTH * WEATHER_BACKGROUND_LOW_HEIGHT)

extern const uint8_t weather_backgrounds_l8
    [WEATHER_BACKGROUND_COUNT][WEATHER_BACKGROUND_LOW_BYTES];
extern const uint32_t weather_background_clut[256];

#endif /* WEATHER_BACKGROUNDS_H */
